name: 'Perform Snapshot Tests'
description: 'This action contains all the usual steps needed to perform the snapshot tests'

inputs:
  github-token:
    description: 'The GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        brew install jq

    - name: Run Snapshot Tests
      shell: bash
      run: run_snapshot_tests.sh

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}