name: 'Perform Tests'
description: 'This action contains all the usual steps needed to perform the snapshot tests'

inputs:
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Snapshot Tests
      shell: bash
      run: |
        xcodebuild test -scheme EcosiaSnapshotTests -testPlan EcosiaSnapshotTests -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}