name: 'Perform Snapshot Tests'
description: 'This action contains all the usual steps needed to perform the snapshot tests'

inputs:
  github-token:
    description: 'The GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up environment
      shell: bash
      run: |
        brew install jq

    - name: Fix-up private Github URLs
      shell: bash
      run: find . -type f \( -name '*.pbxproj' -o -name 'Package.swift' -o -name 'Package.resolved' \) -exec sed -i '' "s/https:\/\/github.com\/${GITHUB_REPOSITORY_OWNER}/https:\/\/${GITHUB_ACCESS_TOKEN}@github.com\/${GITHUB_REPOSITORY_OWNER}/g" {} \;
      env:
        GITHUB_ACCESS_TOKEN: ${{ inputs.github-token }}

    - name: Run Snapshot Tests
      shell: bash
      run: sh ./perform_snapshot_tests.sh

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}