name: 'Perform Snapshot Tests'
description: 'This action contains all the usual steps needed to perform the snapshot tests'

inputs:
  github-token:
    description: 'The GitHub Token'
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up environment
      shell: bash
      run: |
        brew install jq
        brew install chargepoint/xcparse/xcparse
        
    - name: Run Snapshot Tests
      shell: bash
      run: |
        mkdir -p EcosiaTests/Results/
        sh ./perform_snapshot_tests.sh "EcosiaTests/SnapshotTests/snapshot_configuration.json" "EcosiaTests/SnapshotTests/environment.json" "EcosiaTests/Results" "EcosiaSnapshotTests"

    - name: Convert XCResult to JUnit
      run: |
        mkdir -p test_output/xml
        xcparse junit all_tests.xcresult ./test_output/xml
        xcparse attachments all_tests.xcresult ./test_output/attachments

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: './test_output/xml/*.junit'
        github_token: ${{ secrets.GITHUB_TOKEN }}