name: 'Perform Snapshot Tests'
description: 'This action contains all the usual steps needed to perform the snapshot tests'

inputs:
  github-token:
    description: 'The GitHub Token'
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up environment
      shell: bash
      run: |
        brew install jq

    - name: Run Snapshot Tests
      shell: bash
      run: sh ./perform_snapshot_tests.sh

    - name: Process xcresult files
      uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: 'EcosiaTests/Results/'
        output: 'EcosiaTests/Reports/'
        format: 'description'
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: xcresult-reports
        path: EcosiaTests/Reports/