name: 'Perform Test Plan'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  test-plan:
    description: 'The XCTestPlan name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run ${{ inputs.test-plan }} tests if needed
      shell: bash
      run: bundle exec fastlane run run_tests derived_data_path:"BuildDerivedData/" test_without_building:true testplan:"${{ inputs.test-plan }}"

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ secrets.GITHUB_TOKEN }}