name: 'Restore Derived data'
description: 'This action contains all the logic needed to restore the derived data cache'

runs:
  using: "composite"
  steps:

    - name: Restore derived data main branch cache
      uses: actions/cache/restore@v3
      with:
        path: DerivedData/
        key: ${{ runner.os }}-derived-data-cache-${{ github.ref_name }}

    - name: Untar derived data main brach
      shell: bash
      run: if [ -f DerivedData/dd.tar ]; then tar xvPpf DerivedData/dd.tar; else echo "No cache file"; fi