name: 'Perform Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  needs-shared-tests:
    description: 'Flag to determine whether the action needs to perform the Shared  module tests'
    required: true
  needs-storage-tests:
    description: 'Flag to determine whether the action needs to perform the Storage module tests'
    required: true
  needs-client-tests:
    description: 'Flag to determine whether the action needs to perform the Client module tests'
    required: true
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Shared tests if needed
      shell: bash
      run: |
      bool_values=(${{ inputs.needs-shared-tests }} ${{ inputs.needs-storage-tests }} ${{ inputs.needs-client-tests }})
      strings=("SharedTests" "StorageTests" "ClientTests")

      tests_to_run=""

      # Iterate over the boolean values and strings
      for i in "${!bool_values[@]}"; do
          if [[ "${bool_values[$i]}" == "true" ]]; then
              if [[ -z "$tests_to_run" ]]; then
                  tests_to_run="${strings[$i]}"
              else
                  tests_to_run+=",""${strings[$i]}"
              fi
          fi
      done

      bundle exec fastlane run run_tests derived_data_path:"BuildDerivedData" only_testing:"$tests_to_run"

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}