name: 'Perform Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run tests based on file changes
      shell: bash
      run: |
        bundle exec fastlane run run_tests build_for_testing:true
        bundle exec fastlane run run_tests test_without_building:true prelaunch_simulator:true testplan:"UnitTest"

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}