name: 'Perform Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  test-bundles:
    description: 'Flag to determine whether the action needs to perform the Shared  module tests'
    required: false
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Shared tests if needed
      shell: bash
      if: inputs.needs-shared-tests == 'true'
      run: bundle exec fastlane run run_tests derived_data_path:"BuildDerivedData/" test_without_building:true only_testing:SharedTests ClientTests

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}