name: 'Perform Test Plans'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  needs-shared-tests:
    description: 'Flag to determine whether the action needs to perform the Shared  module tests'
    required: true
  needs-storage-tests:
    description: 'Flag to determine whether the action needs to perform the Storage module tests'
    required: true
  needs-client-tests:
    description: 'Flag to determine whether the action needs to perform the Client module tests'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Shared tests if needed
      shell: bash
      if: inputs.needs-shared-tests == 'true'
      uses: ./.github/actions/perform_test_plan
        with:
          test-plan: SharedTestPlan

    - name: Run Storage tests if needed
      shell: bash
      if: inputs.needs-storage-tests == 'true'
      uses: ./.github/actions/perform_test_plan
        with:
          test-plan: StorageTestPlan

    - name: Run Client tests if needed
      shell: bash
      if: inputs.needs-client-tests == 'true'
      uses: ./.github/actions/perform_test_plan
        with:
          test-plan: ClientTestPlan