name: 'Perform Unit Tests'
description: 'This action contains all the usual steps needed to perform the unit tests'

inputs:
  github-token:
    description: 'The Github Token'
    required: true

runs:
  using: "composite"
  steps:

    - name: Run Unit Tests
      shell: bash
      run: |
        bundle exec fastlane run run_tests prelaunch_simulator:true testplan:"UnitTest"
        bundle exec fastlane run run_tests prelaunch_simulator:true scheme:"EcosiaFramework" only_testing:"EcosiaTests"

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3.7.6
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ inputs.github-token }}