name: Build for testing

on:
  workflow_call:
    inputs:
        developer-dir:
            required: true
            type: string

jobs:    
  build_for_testing:
    runs-on: macos-13
    name: Build App
    env:
      DEVELOPER_DIR: ${{ inputs.developer-dir }}

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare_environment
        with:
          core-token: ${{ secrets.IOS_CORE_TOKEN }}

      - name: Build for testing
        run: bundle exec fastlane build

      - name: Update derived data cache
        uses: ./.github/actions/save_derived_data