name: Build for testing

on:
  workflow_call:
    inputs:
        developer-dir:
            required: true
            type: string

jobs:    
  build_for_testing:
    runs-on: macos-latest
    name: Build App
    env:
      DEVELOPER_DIR: ${{ inputs.developer-dir }}

    steps:
  
    - name: Build for testing
      run: bundle exec fastlane build_and_export_derived_data_path

    - name: Update derived data cache
      uses: actions/cache/save@v3
      with:
        path: ${{ steps.get_derived_data_path.outputs.derived_data_path_from_file }}
        key: ${{ runner.os }}-derived-data-cache-${{ github.run_id }}

    - name: Save SPM Cache if needed
      if: steps.restore-spm-cache.outputs.cache-hit == 'false'
      uses: actions/cache/save@v3
      with:
        path: SourcePackages/
        key: ${{ runner.os }}-spm-cache-${{ hashFiles('Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}  