name: Merge Unit Tests

on:
  push:
    branches: [ MOB-2012_firefox_120_upgrade ]


jobs:
  execute_merge_tests:
    runs-on: macos-14
    name: Execute Merge Tests
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare_environment
        with:
          core-token: ${{ secrets.IOS_CORE_TOKEN }}

      # lot of people are experiencing the same issue apparently
      # found a workaround here https://github.com/actions/runner-images/issues/9577
      - name: Delete Xcode.app
        run: sudo rm -rf /Applications/Xcode.app

      - name: Perform Tests and Publish Test reports
        id: perform-tests
        uses: ./.github/actions/perform_tests
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}