name: Merge Unit Tests

on:
  push:
    branches: [ MOB-2012_firefox_120_upgrade ]


jobs:
  execute_merge_tests:
    runs-on: macos-14
    name: Execute Merge Tests
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.3.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare environment
        uses: ./.github/actions/prepare_environment
        with:
          core-token: ${{ secrets.IOS_CORE_TOKEN }}

      - name: Run tests
        shell: bash
        run: |
          # Workaround to make the DerivedData work properly and
          # the simulator to speed up properly 
          # Issue seen both local machines + CIs
          bundle exec fastlane run run_tests build_for_testing:true
          bundle exec fastlane run run_tests test_without_building:true prelaunch_simulator:true testplan:"UnitTest"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.6
        with:
          report_paths: '**/test_output/xml/report.junit'
          github_token: ${{ inputs.github-token }}