name: Regression Tests

on:
  push:
    branches: [ main ]

jobs:
  build_for_testing:
    uses: ./.github/workflows/BuildForTesting.yml
    with:
      developer-dir: /Applications/Xcode_14.2.0.app/Contents/Developer
    secrets: inherit

  execute_regression_tests:
    name: Execure regression tests
    needs: build_for_testing
    uses: ./.github/workflows/ExecuteTestPlan.yml
    with:
      test-plan: MaindTestPlan
      developer-dir: /Applications/Xcode_14.2.0.app/Contents/Developer
    secrets: inherit