name: SwiftLint
on: push
  # pull_request:
  #   branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest

    steps:
    - uses: actions/checkout@v3

    - name: SwiftLint
      run: |
        swiftlint --reporter github-actions-logging --strict