name: SwiftLint
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:5.5-latest

    steps:
    - uses: actions/checkout@v3

    - name: SwiftLint
      run: |
        swiftlint --reporter github-actions-logging --strict