name: UnitTests

on:
  push:
    branches: [ fix-unit-tests-2 ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/cache@v2
      id: cache-npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: install node modules
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install
    - name: run node modules
      run: npm run build
    - uses: actions/cache@v2
      id: cache-carthage
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
    - uses: olejnjak/carthage-workaround@v1
      if: steps.cache-carthage.outputs.cache-hit != 'true'
      with:
        action: bootstrap application-services --platform iOS --cache-builds
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Clean Packages
      run: xcodebuild -scheme Ecosia -project Client.xcodeproj clean
    - name: clone translations
      run: git clone https://github.com/mozilla-mobile/ios-l10n-scripts.git || exit 1
    - name: import locales
      run: ./ios-l10n-scripts/import-locales-firefox.sh --release
    - name: setup content blocking scripts
      run: (cd content-blocker-lib-ios/ContentBlockerGen && swift run)
    - name: Run unit tests
      run: bundle exec fastlane scan
