name: UnitTests

on:
  push:
    branches: [ main, main-39 ]
  pull_request:
    branches: [ main, main-39, main-104 ]

jobs:
  test:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.0.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: install pip modules
      run: |
         python3 -m pip install virtualenv
    - name: install gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - uses: bahmutov/npm-install@v1.6.0
    - run: ./content_blocker_update.sh
    - name: fix up private Github URLs
      run: find . -type f \( -name '*.pbxproj' -o -name 'Package.swift' -o -name 'Package.resolved' \) -exec sed -i '' "s/https:\/\/github.com\/${GITHUB_REPOSITORY_OWNER}/https:\/\/${GITHUB_ACCESS_TOKEN}@github.com\/${GITHUB_REPOSITORY_OWNER}/g" {} \;
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.IOS_CORE_TOKEN }}
    - name: Create empty Staging xcconfig
      run: touch Client/Configuration/Staging.xcconfig
    - name: clean packages
      run: xcodebuild -scheme Ecosia -project Client.xcodeproj clean
    - name: run unit tests
      run: bundle exec fastlane scan
    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**/test_output/xml/report.junit'
        github_token: ${{ secrets.GITHUB_TOKEN }}
