name: Release Notes update

on:
  push:
    paths:
      - 'fastlane/metadata/**'
      - '!fastlane/metadata/en-US/**'
    branches: [ MOB-1977_fully_automated_release_notes ]

jobs:
  upload_release_notes_to_appstore:
    runs-on: ubuntu-latest
    name: Upload release notes to AppStore

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
    
      - name: Fastlane upload release notes
        run: |
            CURRENT_VERSION=$(grep 'MARKETING_VERSION' Client/Configuration/Common.xcconfig | cut -d ' ' -f3)
            echo $CURRENT_VERSION
            # bundle exec fastlane deliver --app-version $CURRENT_VERSION