name: Release Notes update

on:
  pull_request:
    paths:
      - 'fastlane/metadata/**'
      - '!fastlane/metadata/en-US/**'
    branches: [ main ]

jobs:
  upload_release_notes_to_appstore:
    runs-on: ubuntu-latest
    name: Upload release notes to AppStore

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
  
      - name: Install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
    
      - name: Fastlane upload release notes
        run: |
            CURRENT_VERSION=$(grep 'MARKETING_VERSION' Client/Configuration/Common.xcconfig | cut -d ' ' -f3)
            bundle exec fastlane deliver --app-version $CURRENT_VERSION